export const LOAD_POKEMON = "LOAD_POKEMON"
export const LOAD_LOADING_POKEMON = "LOAD_LOADING_POKEMON"
export const FILTERED_POKEMON = "FILTERED_POKEMON"
export const SEARCH_POKEMON = "SEARCH_POKEMON"

export const LOAD_DETAIL_POKEMON = "LOAD_DETAIL_POKEMON"
export const LOAD_DETAIL_LOADING_POKEMON = "LOAD_DETAIL_LOADING_POKEMON"

export const ADD_FAVOURITE = "ADD_FAVOURITE"
export const DELETE_FAVOURITE = "DELETE_FAVOURITE"
export const LOAD_FAVOURITE = "LOAD_FAVOURITE"
export const LOAD_LOADING_FAVOURITE = "LOAD_LOADING_FAVOURITE"