export const LOAD_POKEMON = "LOAD_POKEMON"
export const LOAD_LOADING_POKEMON = "LOAD_LOADING_POKEMON"
export const FILTERED_POKEMON = "FILTERED_POKEMON"

export const LOAD_DETAIL_POKEMON = "LOAD_DETAIL_POKEMON"
export const LOAD_DETAIL_LOADING_POKEMON = "LOAD_DETAIL_LOADING_POKEMON"

export const ADD_WISHLIST = "ADD_WISHLIST"
export const DELETE_WISHLIST = "DELETE_WISHLIST"
export const LOAD_WISHLIST = "LOAD_WISHLIST"
export const LOAD_LOADING_WISHLIST = "LOAD_LOADING_WISHLIST"